TestCase = Reject test failing {
  TestError: A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks

  Try: add .catch() in the server/route file
  e.g.then(result => {
        res.status(201).json(result) 
      })
      // .catch(() => res.sendStatus(500))

}

TestCase =  All tests failing {
  TestError: connect ECONNREFUSED 127.0.0.1:80

  Try: check if the correct route is being called, the URl is likely wrong, check for a leading /
  e.g: (/api/v1/routeName) instead of (api/vi/routeName)
}


TestCase = Tests other than .get test are failing {
  TestError: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - 
  Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

  Try:  the routes/server should return with .json() after the res.status()
  e.g .then(details => {res.status(201).json(details)
}